#!/bin/bash

# the while statement continually executes a block of statements while a particular condition is true or met

count=0
num=10
# -lt == les than
while [ $count -lt 10 ]
do
 echo 
 echo $num seconds left to stop this process
 echo
 sleep 1

num=`expr $num - 1`
count=`expr $count + 1`
done
echo
echo process is stopped!!!
echo
