#!/bin/bash


# ping to multiple host from host file

hosts="/home/centos/shell_1/host.txt"

for ip in $(cat $hosts)
do
ping -c1 $ip &> /dev/null
if [ $? -eq 0 ]
	then
	echo $ip is ok
	else
	echo $ip is not ok
fi
done
